apiVersion: apps/v1
kind: Deployment
metadata:
  name: papache-val
  namespace: web-val
  labels:
    app: papache-val
spec:
  replicas: 6
  selector:
    matchLabels:
      app: papache-val
  template:
    metadata:
      labels:
        app: papache-val
    spec:
      containers:
        - name: papache-val
          image: httpd:2.4.63-alpine3.22
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
          ports:
            - containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: papache-val-svc
  namespace: web-val
spec:
  type: LoadBalancer
  ports:
    - name: web
      port: 8095
      targetPort: 80
      protocol: TCP
  selector:
    app: papache-val
